// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type NewUser struct {
	Email        string  `json:"email"`
	Token        string  `json:"token"`
	AuthMethodID int     `json:"authMethodId"`
	FirstName    *string `json:"firstName"`
	LastName     *string `json:"lastName"`
	DateOfBirth  *string `json:"dateOfBirth"`
}

type UpdatedProfile struct {
	FirstName   *string `json:"firstName"`
	LastName    *string `json:"lastName"`
	DateOfBirth *string `json:"dateOfBirth"`
}

type User struct {
	Email       string       `json:"email"`
	Role        int          `json:"role"`
	CreatedAt   *string      `json:"createdAt"`
	UpdatedAt   *string      `json:"updatedAt"`
	UserProfile *UserProfile `json:"userProfile"`
}

type UserProfile struct {
	FirstName   *string `json:"firstName"`
	LastName    *string `json:"lastName"`
	DateOfBirth *string `json:"dateOfBirth"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   *string `json:"updatedAt"`
}
