version: '3.1'

volumes:
  database_data:
    driver: local
  redis_data:
    driver: local

services:
  redis:
    container_name: bitkiosk-redis
    image: redis
    ports:
      - 6379:6379
  postgres:
    container_name:
      bitkiosk-postgres
    image: postgres:alpine
    volumes: ["./database_data:/var/lib/postgres/data"]
    restart: always
    environment:
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'bitkiosk'
    ports:
      - 5432:5432